[package]
name = "ip-spoof"
version = "0.1.0"
edition = "2021"
description = "LD_PRELOAD library for Veilid devnet IP translation"

[lib]
name = "ipspoof"
crate-type = ["dylib"]

[dependencies]
redhook = "2.0"
libc = "0.2"
